import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    name: 'English',
    flag: '🇬🇧',
    loginTitle: 'Sign in to IDP Platform',
    loginSubtitle: 'Enterprise Intelligent Document Processing powered by AI',
    emailLabel: 'Email Address',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    signInBtn: 'Sign In to Account',
    noAccount: "Don't have an account?",
    createAccountLink: 'Create an Account',
    demoAdminLogin: 'Quick Demo Admin',
    demoUserLogin: 'Quick Demo User',
    registerTitle: 'Create your account',
    registerSubtitle: 'Start processing invoices, contracts, and documents automatically',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'John Doe',
    roleLabel: 'Account Role',
    roleUser: 'User (Upload & Analyze)',
    roleAdmin: 'Administrator (Full Access)',
    signUpBtn: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    signInLink: 'Sign In',
    navDashboard: 'Dashboard',
    navUpload: 'Upload Document',
    navHistory: 'History & Archive',
    navSearch: 'Global Search',
    navChat: 'AI Document Chat',
    navAdmin: 'Admin Console',
    navProfile: 'My Profile',
    navSettings: 'Settings',
    logoutBtn: 'Sign Out',
    selectLanguage: 'Select Language',
    totalDocsCard: 'Total Documents',
    storageCard: 'Total Storage Used',
    ocrCountCard: 'OCR Processed',
    completionRateCard: 'Processing Success',
    recentActivity: 'Recent Processing Activity',
    quickUploadBtn: 'Upload New File',
    uploadTitle: 'Intelligent Document Upload',
    uploadSubtitle: 'Upload PDF, DOCX, Scanned Images, or Text files for automated AI extraction & OCR',
    dragDropText: 'Drag and drop your file here, or click to browse',
    supportedFormats: 'Supports PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT (Max 50MB)',
    categoryLabel: 'Document Category',
    uploadingBtn: 'Processing & Extracting...',
    uploadStartBtn: 'Upload & Process File'
  },
  te: {
    name: 'తెలుగు (Telugu)',
    flag: '🇮🇳',
    loginTitle: 'IDP ప్లాట్‌ఫారమ్‌కు లాగిన్ అవ్వండి',
    loginSubtitle: 'AI ద్వారా నడిచే ఇంటెలిజెంట్ డాక్యుమెంట్ ప్రాసెసింగ్',
    emailLabel: 'ఈమెయిల్ చిరునామా',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'పాస్‌వర్డ్',
    passwordPlaceholder: '••••••••',
    signInBtn: 'ఖాతాలోకి సైన్ ఇన్ అవ్వండి',
    noAccount: 'ఖాతా లేదా?',
    createAccountLink: 'ఖాతాను సృష్టించండి',
    demoAdminLogin: 'త్వరిత డెమో అడ్మిన్',
    demoUserLogin: 'త్వరిత డెమో యూజర్',
    registerTitle: 'మీ ఖాతాను సృష్టించండి',
    registerSubtitle: 'ఇన్‌వాయిస్‌లు, ఒప్పందాలు మరియు పత్రాలను స్వయంచాలకంగా ప్రాసెస్ చేయండి',
    fullNameLabel: 'పూర్తి పేరు',
    fullNamePlaceholder: 'అఖిల్ గట్ల',
    roleLabel: 'ఖాతా పాత్ర',
    roleUser: 'యూజర్ (అప్‌లోడ్ & విశ్లేషణ)',
    roleAdmin: 'అడ్మినిస్ట్రేటర్ (పూర్తి యాక్సెస్)',
    signUpBtn: 'ఖాతాను సృష్టించండి',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    signInLink: 'సైన్ ఇన్ అవ్వండి',
    navDashboard: 'డాష్‌బోర్డ్',
    navUpload: 'డాక్యుమెంట్ అప్‌లోడ్',
    navHistory: 'చరిత్ర & ఆర్కైవ్',
    navSearch: 'గ్లోబల్ సెర్చ్',
    navChat: 'AI డాక్యుమెంట్ చాట్',
    navAdmin: 'అడ్మిన్ కన్సోల్',
    navProfile: 'నా ప్రొఫైల్',
    navSettings: 'సెట్టింగ్‌లు',
    logoutBtn: 'లాగౌట్',
    selectLanguage: 'భాషను ఎంచుకోండి',
    totalDocsCard: 'మొత్తం డాక్యుమెంట్లు',
    storageCard: 'ఉపయోగించిన స్టోరేజ్',
    ocrCountCard: 'OCR ప్రాసెస్ చేయబడింది',
    completionRateCard: 'ప్రాసెసింగ్ విజయం',
    recentActivity: 'ఇటీవలి ప్రాసెసింగ్ కార్యాచరణ',
    quickUploadBtn: 'కొత్త ఫైల్‌ను అప్‌లోడ్ చేయండి',
    uploadTitle: 'ఇంటెలిజెంట్ డాక్యుమెంట్ అప్‌లోడ్',
    uploadSubtitle: 'AI ఎక్స్‌ట్రాక్షన్ & OCR కోసం PDF, DOCX, స్కాన్ చేసిన చిత్రాలను అప్‌లోడ్ చేయండి',
    dragDropText: 'మీ ఫైల్‌ను ఇక్కడ డ్రాగ్ చేసి డ్రాప్ చేయండి లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT మద్దతు ఇస్తుంది (గరిష్టంగా 50MB)',
    categoryLabel: 'డాక్యుమెంట్ వర్గం',
    uploadingBtn: 'ప్రాసెసింగ్ & ఎక్స్‌ట్రాక్టింగ్...',
    uploadStartBtn: 'ఫైల్‌ను అప్‌లోడ్ & ప్రాసెస్ చేయండి'
  },
  hi: {
    name: 'हिंदी (Hindi)',
    flag: '🇮🇳',
    loginTitle: 'IDP प्लेटफॉर्म में लॉगिन करें',
    loginSubtitle: 'एआई द्वारा संचालित इंटेलिजेंट डॉक्यूमेंट प्रोसेसिंग',
    emailLabel: 'ईमेल पता',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'पासवर्ड',
    passwordPlaceholder: '••••••••',
    signInBtn: 'साइन इन करें',
    noAccount: 'खाता नहीं है?',
    createAccountLink: 'खाता बनाएं',
    demoAdminLogin: 'डेमो एडमिन लॉगिन',
    demoUserLogin: 'डेमो यूजर लॉगिन',
    registerTitle: 'अपना खाता बनाएं',
    registerSubtitle: 'इनवॉइस, अनुबंध और दस्तावेज़ों को स्वचालित रूप से प्रोसेस करें',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'अखिल शर्मा',
    roleLabel: 'खाता भूमिका',
    roleUser: 'उपयोगकर्ता (अपलोड और विश्लेषण)',
    roleAdmin: 'प्रशासक (पूर्ण पहुंच)',
    signUpBtn: 'खाता बनाएं',
    alreadyHaveAccount: 'पहले से ही एक खाता है?',
    signInLink: 'साइन इन करें',
    navDashboard: 'डैशबोर्ड',
    navUpload: 'दस्तावेज़ अपलोड करें',
    navHistory: 'इतिहास और संग्रह',
    navSearch: 'ग्लोबल खोज',
    navChat: 'एआई दस्तावेज़ चैट',
    navAdmin: 'एडमिन कंसोल',
    navProfile: 'मेरी प्रोफ़ाइल',
    navSettings: 'सेटिंग्स',
    logoutBtn: 'लॉगआउट',
    selectLanguage: 'भाषा चुनें',
    totalDocsCard: 'कुल दस्तावेज़',
    storageCard: 'कुल प्रयुक्त स्टोरेज',
    ocrCountCard: 'ओसीआर प्रोसेस किया गया',
    completionRateCard: 'प्रसंस्करण सफलता दर',
    recentActivity: 'हाल की प्रसंस्करण गतिविधि',
    quickUploadBtn: 'नई फ़ाइल अपलोड करें',
    uploadTitle: 'इंटेलिजेंट दस्तावेज़ अपलोड',
    uploadSubtitle: 'एआई एक्सट्रैक्शन और ओसीआर के लिए पीडीएफ, डॉक्स, स्कैन की गई छवियां अपलोड करें',
    dragDropText: 'अपनी फ़ाइल यहां खींचें और छोड़ें, या ब्राउज़ करने के लिए क्लिक करें',
    supportedFormats: 'पीडीएफ, डॉक्स, पीएनजी, जेपीजी, वेबपी, टेक्स्ट सपोर्ट (अधिकतम 50MB)',
    categoryLabel: 'दस्तावेज़ श्रेणी',
    uploadingBtn: 'प्रोसेसिंग और निष्कर्षण जारी है...',
    uploadStartBtn: 'फ़ाइल अपलोड और प्रोसेस करें'
  },
  ta: {
    name: 'தமிழ் (Tamil)',
    flag: '🇮🇳',
    loginTitle: 'IDP தளத்தில் உள்நுழைக',
    loginSubtitle: 'செயற்கை நுண்ணறிவு ఆధారিত ஆவண செயலாக்கம்',
    emailLabel: 'மின்னஞ்சல் முகவரி',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'கடவுச்சொல்',
    passwordPlaceholder: '••••••••',
    signInBtn: 'உள்நுழைக',
    noAccount: 'கணக்கு இல்லையா?',
    createAccountLink: 'கணக்கை உருவாக்கு',
    demoAdminLogin: 'டெமோ நிர்வாகி',
    demoUserLogin: 'டெமோ பயனர்',
    registerTitle: 'உங்கள் கணக்கை உருவாக்குங்கள்',
    registerSubtitle: 'இன்வாய்ஸ்கள் மற்றும் ஆவணங்களை தானாக செயலாக்குங்கள்',
    fullNameLabel: 'முழு பெயர்',
    fullNamePlaceholder: 'கார்த்திக்',
    roleLabel: 'கணக்கு பங்கு',
    roleUser: 'பயனர் (பதிவேற்றம் & பகுப்பாய்வு)',
    roleAdmin: 'நிர்வாகி (முழு அணுகல்)',
    signUpBtn: 'கணக்கை உருவாக்கு',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    signInLink: 'உள்நுழைக',
    navDashboard: 'டாஷ்போர்டு',
    navUpload: 'ஆவணம் பதிவேற்று',
    navHistory: 'வரலாறு & காப்பகம்',
    navSearch: 'தேடல்',
    navChat: 'AI ஆவண அரட்டை',
    navAdmin: 'நிர்வாக அரங்கம்',
    navProfile: 'என் சுயவிவரம்',
    navSettings: 'அமைப்புகள்',
    logoutBtn: 'வெளியேறு',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    totalDocsCard: 'மொத்த ஆவணங்கள்',
    storageCard: 'பயன்படுத்தப்பட்ட சேமிப்பகம்',
    ocrCountCard: 'OCR செயலாக்கப்பட்டது',
    completionRateCard: 'வெற்றி விகிதம்',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    quickUploadBtn: 'புதிய கோப்பை பதிவேற்று',
    uploadTitle: 'புத்திசாலித்தனமான ஆவண பதிவேற்றம்',
    uploadSubtitle: 'AI பிரித்தெடுப்பிற்கு PDF, DOCX மற்றும் படங்களை பதிவேற்றவும்',
    dragDropText: 'உங்கள் கோப்பை இங்கே இழுத்து விடுங்கள் அல்லது உலாவ கிளிக் செய்யவும்',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT ஐ ஆதரிக்கிறது (அதிகபட்சம் 50MB)',
    categoryLabel: 'ஆவண வகை',
    uploadingBtn: 'செயலாக்கப்படுகிறது...',
    uploadStartBtn: 'கோப்பை பதிவேற்றி செயலாக்கு'
  },
  kn: {
    name: 'ಕನ್ನಡ (Kannada)',
    flag: '🇮🇳',
    loginTitle: 'IDP ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
    loginSubtitle: 'AI ಚಾಲಿತ ಬುದ್ಧಿವಂತ ಡಾಕ್ಯುಮೆಂಟ್ ಪ್ರೊಸೆಸಿಂಗ್',
    emailLabel: 'ಇಮೇಲ್ ವಿಳಾಸ',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'ಪಾಸ್‌ವರ್ಡ್',
    passwordPlaceholder: '••••••••',
    signInBtn: 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    createAccountLink: 'ಖಾತೆಯನ್ನು ರಚಿಸಿ',
    demoAdminLogin: 'ಡೆಮೊ ಅಡ್ಮಿನ್',
    demoUserLogin: 'ಡೆಮೊ ಬಳಕೆದಾರ',
    registerTitle: 'ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಚಿಸಿ',
    registerSubtitle: 'ಇನ್‌ವಾಯ್ಸ್‌ಗಳು ಮತ್ತು ದಾಖಲೆಗಳನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿ',
    fullNameLabel: 'ಪೂರ್ಣ ಹೆಸರು',
    fullNamePlaceholder: 'ಸುರೇಶ್',
    roleLabel: 'ಖಾತೆಯ ಪಾತ್ರ',
    roleUser: 'ಬಳಕೆದಾರ (ಅಪ್‌ಲೋಡ್ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ)',
    roleAdmin: 'ಅಡ್ಮಿನಿಸ್ಟ್ರೇಟರ್ (ಪೂರ್ಣ ಪ್ರವೇಶ)',
    signUpBtn: 'ಖಾತೆ ರಚಿಸಿ',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    signInLink: 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    navDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    navUpload: 'ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್‌ಲೋಡ್',
    navHistory: 'ಇತಿಹಾಸ ಮತ್ತು ಆರ್ಕೈವ್',
    navSearch: 'ಹುಡುಕಾಟ',
    navChat: 'AI ಡಾಕ್ಯುಮೆಂಟ್ ಚಾಟ್',
    navAdmin: 'ಅಡ್ಮಿನ್ ಕನ್ಸೋಲ್',
    navProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    navSettings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    logoutBtn: 'ಸೈನ್ ಔಟ್',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    totalDocsCard: 'ಒಟ್ಟು ದಾಖಲೆಗಳು',
    storageCard: 'ಬಳಸಿದ ಸಂಗ್ರಹಣೆ',
    ocrCountCard: 'OCR ಸಂಸ್ಕರಿಸಲಾಗಿದೆ',
    completionRateCard: 'ಯಶಸ್ಸಿನ ಪ್ರಮಾಣ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಪ್ರಕ್ರಿಯೆ ಚಟುವಟಿಕೆ',
    quickUploadBtn: 'ಹೊಸ ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    uploadTitle: 'ಬುದ್ಧಿವಂತ ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್‌ಲೋಡ್',
    uploadSubtitle: 'AI ಹೊರತೆಗೆಯುವಿಕೆಗಾಗಿ PDF, DOCX ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    dragDropText: 'ನಿಮ್ಮ ಫೈಲ್ ಅನ್ನು ಇಲ್ಲಿ ಎಳೆಯಿರಿ ಅಥವಾ ಬ್ರೌಸ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT ಬೆಂಬಲಿಸುತ್ತದೆ (ಗರಿಷ್ಠ 50MB)',
    categoryLabel: 'ದಾಖಲೆ ವರ್ಗ',
    uploadingBtn: 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...',
    uploadStartBtn: 'ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿ'
  },
  ml: {
    name: 'മലയാളം (Malayalam)',
    flag: '🇮🇳',
    loginTitle: 'IDP പ്ലാറ്റ്‌ഫോമിലേക്ക് ലോഗിൻ ചെയ്യുക',
    loginSubtitle: 'AI കരുത്തേകിയ ഇന്റലിജന്റ് ഡോക്യുമെന്റ് പ്രോസസ്സിംഗ്',
    emailLabel: 'ഇമെയിൽ വിലാസം',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'പാസ്‌വേഡ്',
    passwordPlaceholder: '••••••••',
    signInBtn: 'സൈൻ ഇൻ ചെയ്യുക',
    noAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    createAccountLink: 'അക്കൗണ്ട് ഉണ്ടാക്കൂ',
    demoAdminLogin: 'ഡെമോ അഡ്മിൻ',
    demoUserLogin: 'ഡെമോ യൂസർ',
    registerTitle: 'നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്‌ടിക്കുക',
    registerSubtitle: 'ഇൻവോയ്‌സുകളും പ്രമാണങ്ങളും സ്വയമേവ പ്രോസസ്സ് ചെയ്യുക',
    fullNameLabel: 'പൂർണ്ണമായ പേര്',
    fullNamePlaceholder: 'രാഹുൽ',
    roleLabel: 'അക്കൗണ്ട് റോൾ',
    roleUser: 'ഉപയോക്താവ് (അപ്‌ലോഡ് & വിശകലനം)',
    roleAdmin: 'അഡ്മിനിസ്ട്രേറ്റർ (പൂർണ്ണ ആക്സസ്)',
    signUpBtn: 'അക്കൗണ്ട് ഉണ്ടാക്കൂ',
    alreadyHaveAccount: 'നേരത്തെ തന്നെയൊരു അക്കൗണ്ടുണ്ടോ?',
    signInLink: 'സൈൻ ഇൻ ചെയ്യുക',
    navDashboard: 'ഡാഷ്‌ബോർഡ്',
    navUpload: 'ഡോക്യുമെന്റ് അപ്‌ലോഡ്',
    navHistory: 'ചരിത്രവും ശേഖരവും',
    navSearch: 'തിരച്ചിൽ',
    navChat: 'AI ഡോക്യുമെന്റ് ചാറ്റ്',
    navAdmin: 'അഡ്മിൻ കൺസോൾ',
    navProfile: 'എന്റെ പ്രൊഫൈൽ',
    navSettings: 'ക്രമീകരണങ്ങൾ',
    logoutBtn: 'സൈൻ ഔട്ട്',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    totalDocsCard: 'ആകെ ഡോക്യുമെന്റുകൾ',
    storageCard: 'ഉപയോഗിച്ച സംഭരണം',
    ocrCountCard: 'OCR പ്രോസസ്സ് ചെയ്തു',
    completionRateCard: 'വിജയ ശതമാനം',
    recentActivity: 'സമീപകാല പ്രവർത്തനം',
    quickUploadBtn: 'പുതിയ ഫയൽ അപ്‌ലോഡ് ചെയ്യുക',
    uploadTitle: 'ഇന്റലിജന്റ് ഡോക്യുമെന്റ് അപ്‌ലോഡ്',
    uploadSubtitle: 'AI എക്‌സ്‌ട്രാക്‌ഷനായി PDF, DOCX, ചിത്രങ്ങൾ എന്നിവ അപ്‌ലോഡ് ചെയ്യുക',
    dragDropText: 'നിങ്ങളുടെ ഫയൽ ഇവിടെ ഇടുക അല്ലെങ്കിൽ ബ്രൗസ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT പിന്തുണയ്ക്കുന്നു (പരമാവധി 50MB)',
    categoryLabel: 'ഡോക്യുമെന്റ് വിഭാഗം',
    uploadingBtn: 'പ്രോസസ്സ് ചെയ്യുന്നു...',
    uploadStartBtn: 'ഫയൽ അപ്‌ലോഡ് ചെയ്തു പ്രോസസ്സ് ചെയ്യുക'
  },
  mr: {
    name: 'मराठी (Marathi)',
    flag: '🇮🇳',
    loginTitle: 'IDP प्लॅटफॉर्मवर लॉगिन करा',
    loginSubtitle: 'AI द्वारा संचलित इंटेलिजेंट दस्तऐवज प्रक्रिया',
    emailLabel: 'ईमेल पत्ता',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'पासवर्ड',
    passwordPlaceholder: '••••••••',
    signInBtn: 'साइन इन करा',
    noAccount: 'खाते नाही?',
    createAccountLink: 'खाते तयार करा',
    demoAdminLogin: 'डेमो ॲडमिन लॉगिन',
    demoUserLogin: 'डेमो युझर लॉगिन',
    registerTitle: 'तुमचे खाते तयार करा',
    registerSubtitle: 'इनव्हॉइस आणि दस्तऐवजांवर स्वयंचलित प्रक्रिया करा',
    fullNameLabel: 'पूर्ण नाव',
    fullNamePlaceholder: 'सचिन पाटील',
    roleLabel: 'खाते भूमिका',
    roleUser: 'वापरकर्ता (अपलोड आणि विश्लेषण)',
    roleAdmin: 'प्रशासक (पूर्ण प्रवेश)',
    signUpBtn: 'खाते तयार करा',
    alreadyHaveAccount: 'आधीच खाते आहे?',
    signInLink: 'साइन इन करा',
    navDashboard: 'डॅशबोर्ड',
    navUpload: 'दस्तऐवज अपलोड करा',
    navHistory: 'इतिहास आणि दस्तऐवज संग्रह',
    navSearch: 'शोधा',
    navChat: 'AI दस्तऐवज चॅट',
    navAdmin: 'ॲडमिन कन्सोल',
    navProfile: 'माझे प्रोफाईल',
    navSettings: 'सेटिंग्ज',
    logoutBtn: 'साइन आउट करा',
    selectLanguage: 'भाषा निवडा',
    totalDocsCard: 'एकूण दस्तऐवज',
    storageCard: 'वापरलेले स्टोरेज',
    ocrCountCard: 'OCR प्रक्रिया केली',
    completionRateCard: 'यशस्वी दर',
    recentActivity: 'अलीकडील प्रक्रिया कार्ये',
    quickUploadBtn: 'नवीन फाईल अपलोड करा',
    uploadTitle: 'इंटेलिजेंट दस्तऐवज अपलोड',
    uploadSubtitle: 'AI काढण्यासाठी PDF, DOCX आणि स्कॅन केलेल्या इमेज अपलोड करा',
    dragDropText: 'तुमची फाईल येथे ड्रॅग आणि ड्रॉप करा किंवा ब्राउझ करण्यासाठी क्लिक करा',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT ला सपोर्ट करते (कमाल 50MB)',
    categoryLabel: 'दस्तऐवज वर्गवारी',
    uploadingBtn: 'प्रक्रिया सुरू आहे...',
    uploadStartBtn: 'फाईल अपलोड आणि प्रक्रिया करा'
  },
  bn: {
    name: 'বাংলা (Bengali)',
    flag: '🇮🇳',
    loginTitle: 'IDP প্ল্যাটফর্মে লগইন করুন',
    loginSubtitle: 'AI দ্বারা চালিত ইন্টেলিজেন্ট ডকুমেন্ট প্রসেসিং',
    emailLabel: 'ইমেল ঠিকানা',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'পাসওয়ার্ড',
    passwordPlaceholder: '••••••••',
    signInBtn: 'সাইন ইন করুন',
    noAccount: 'অ্যাকাউন্ট নেই?',
    createAccountLink: 'অ্যাকাউন্ট তৈরি করুন',
    demoAdminLogin: 'ডেমো অ্যাডমিন',
    demoUserLogin: 'ডেমো ইউজার',
    registerTitle: 'আপনার অ্যাকাউন্ট তৈরি করুন',
    registerSubtitle: 'ইনভয়েস এবং নথি স্বয়ংক্রিয়ভাবে প্রসেস করুন',
    fullNameLabel: 'পুরো নাম',
    fullNamePlaceholder: 'অভিজিৎ মুখার্জি',
    roleLabel: 'অ্যাকাউন্ট ভূমিকা',
    roleUser: 'ব্যবহারকারী (আপলোড ও বিশ্লেষণ)',
    roleAdmin: 'প্রশাসক (সম্পূর্ণ অ্যাক্সেস)',
    signUpBtn: 'অ্যাকাউন্ট তৈরি করুন',
    alreadyHaveAccount: 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
    signInLink: 'সাইন ইন করুন',
    navDashboard: 'ড্যাশবোর্ড',
    navUpload: 'নথি আপলোড',
    navHistory: 'ইতিহাস ও আর্কাইভ',
    navSearch: 'অনুসন্ধান',
    navChat: 'AI নথি চ্যাট',
    navAdmin: 'অ্যাডমিন কনসোল',
    navProfile: 'আমার প্রোফাইল',
    navSettings: 'সেটিংস',
    logoutBtn: 'সাইন আউট',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    totalDocsCard: 'মোট নথি',
    storageCard: 'ব্যবহৃত স্টোরেজ',
    ocrCountCard: 'OCR প্রক্রিয়াজাত',
    completionRateCard: 'সফলতার হার',
    recentActivity: 'সাম্প্রতিক প্রক্রিয়াকরণ কার্যকলাপ',
    quickUploadBtn: 'নতুন ফাইল আপলোড করুন',
    uploadTitle: 'ইন্টেলিজেন্ট নথি আপলোড',
    uploadSubtitle: 'AI এক্সট্রাকশনের জন্য PDF, DOCX এবং ছবি আপলোড করুন',
    dragDropText: 'আপনার ফাইলটি এখানে ড্র্যাগ এবং ড্রপ করুন বা ব্রাউজ করতে ক্লিক করুন',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT সমর্থন করে (সর্বোচ্চ 50MB)',
    categoryLabel: 'নথির বিভাগ',
    uploadingBtn: 'প্রক্রিয়াকরণ চলছে...',
    uploadStartBtn: 'ফাইল আপলোড ও প্রসেস করুন'
  },
  gu: {
    name: 'ગુજરાતી (Gujarati)',
    flag: '🇮🇳',
    loginTitle: 'IDP પ્લેટફોર્મ પર લોગિન કરો',
    loginSubtitle: 'AI સંચાલિત ઇન્ટેલિજન્ટ દસ્તાવેજ પ્રોસેસિંગ',
    emailLabel: 'ઇમેઇલ સરનામું',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'પાસવર્ડ',
    passwordPlaceholder: '••••••••',
    signInBtn: 'સાઇન ઇન કરો',
    noAccount: 'એકાઉન્ટ નથી?',
    createAccountLink: 'એકાઉન્ટ બનાવો',
    demoAdminLogin: 'ડેમો એડમિન',
    demoUserLogin: 'ડેમો યુઝર',
    registerTitle: 'તમારું એકાઉન્ટ બનાવો',
    registerSubtitle: 'ઇનવોઇસ અને દસ્તાવેજોને આપમેળે પ્રોસેસ કરો',
    fullNameLabel: 'પૂરું નામ',
    fullNamePlaceholder: 'ચિરાગ પટેલ',
    roleLabel: 'એકાઉન્ટ રોલ',
    roleUser: 'વપરાશકર્તા (અપલોડ અને વિશ્લેષણ)',
    roleAdmin: 'એડમિનિસ્ટ્રેટર (પૂર્ણ એક્સેસ)',
    signUpBtn: 'એકાઉન્ટ બનાવો',
    alreadyHaveAccount: 'પહેલેથી જ એકાઉન્ટ છે?',
    signInLink: 'સાઇન ઇન કરો',
    navDashboard: 'ડેશબોર્ડ',
    navUpload: 'દસ્તાવેજ અપલોડ કરો',
    navHistory: 'ઇતિહાસ અને આઇકલાઇવ',
    navSearch: 'શોધો',
    navChat: 'AI દસ્તાવેજ ચેટ',
    navAdmin: 'એડમિન કન્સોલ',
    navProfile: 'મારી પ્રોફાઇલ',
    navSettings: 'સેટિંગ્સ',
    logoutBtn: 'સાઇન આઉટ',
    selectLanguage: 'ભાષા પસંદ કરો',
    totalDocsCard: 'કુલ દસ્તાવેજો',
    storageCard: 'વપરાયેલ સ્ટોરેજ',
    ocrCountCard: 'OCR પ્રોસેસ કરેલ',
    completionRateCard: 'સફળતા દર',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    quickUploadBtn: 'નવી ફાઇલ અપલોડ કરો',
    uploadTitle: 'ઇન્ટેલિજન્ટ દસ્તાવેજ અપલોડ',
    uploadSubtitle: 'AI એક્સટ્રેક્શન માટે PDF, DOCX અને ઇમેજ અપલોડ કરો',
    dragDropText: 'તમારી ફાઇલ અહીં ડ્રેગ અને ડ્રોપ કરો અથવા બ્રાઉઝ કરવા માટે ક્લિક કરો',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT ને સપોર્ટ કરે છે (મહત્તમ 50MB)',
    categoryLabel: 'દસ્તાવેજ કેટેગરી',
    uploadingBtn: 'પ્રોસેસ થઈ રહ્યું છે...',
    uploadStartBtn: 'ફાઇલ અપલોড અને પ્રોસેસ કરો'
  },
  pa: {
    name: 'ਪੰਜਾਬੀ (Punjabi)',
    flag: '🇮🇳',
    loginTitle: 'IDP ਪਲੇਟਫਾਰਮ ਵਿੱਚ ਲੌਗਇਨ ਕਰੋ',
    loginSubtitle: 'AI ਦੁਆਰਾ ਸੰਚਾਲਿਤ ਇੰਟੈਲੀਜੈਂਟ ਦਸਤਾਵੇਜ਼ ਪ੍ਰੋਸੈਸਿੰਗ',
    emailLabel: 'ਈਮੇਲ ਪਤਾ',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'ਪਾਸਵਰਡ',
    passwordPlaceholder: '••••••••',
    signInBtn: 'ਸਾਈਨ ਇਨ ਕਰੋ',
    noAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    createAccountLink: 'ਖਾਤਾ ਬਣਾਓ',
    demoAdminLogin: 'ਡੇਮੋ ਐਡਮਿਨ',
    demoUserLogin: 'ਡੇਮੋ ਯੂਜ਼ਰ',
    registerTitle: 'ਆਪਣਾ ਖਾਤਾ ਬਣਾਓ',
    registerSubtitle: 'ਇਨਵੌਇਸਾਂ ਅਤੇ ਦਸਤਾਵੇਜ਼ਾਂ ਨੂੰ ਆਪਣੇ ਆਪ ਪ੍ਰੋਸੈਸ ਕਰੋ',
    fullNameLabel: 'ਪੂਰਾ ਨਾਮ',
    fullNamePlaceholder: 'ਗੁਰਪ੍ਰੀਤ ਸਿੰਘ',
    roleLabel: 'ਖਾਤਾ ਭੂਮਿਕਾ',
    roleUser: 'ਯੂਜ਼ਰ (ਅੱਪਲੋਡ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ)',
    roleAdmin: 'ਐਡਮਿਨਿਸਟ੍ਰੇਟਰ (ਪੂਰੀ ਪਹੁੰਚ)',
    signUpBtn: 'ਖਾਤਾ ਬਣਾਓ',
    alreadyHaveAccount: 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?',
    signInLink: 'ਸਾਈਨ ਇਨ ਕਰੋ',
    navDashboard: 'ਡੈਸ਼ਬੋਰਡ',
    navUpload: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
    navHistory: 'ਇਤਿਹਾਸ ਅਤੇ ਆਰਕਾਈਵ',
    navSearch: 'ਖੋਜੋ',
    navChat: 'AI ਦਸਤਾਵੇਜ਼ ਚੈਟ',
    navAdmin: 'ਐਡਮਿਨ ਕੰਸੋਲ',
    navProfile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    navSettings: 'ਸੈਟਿੰਗਾਂ',
    logoutBtn: 'ਸਾਈਨ ਆਊਟ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    totalDocsCard: 'ਕੁੱਲ ਦਸਤਾਵੇਜ਼',
    storageCard: 'ਵਰਤੀ ਗਈ ਸਟੋਰੇਜ',
    ocrCountCard: 'OCR ਪ੍ਰੋਸੈਸ ਕੀਤਾ ਗਿਆ',
    completionRateCard: 'ਸਫਲਤਾ ਦੀ ਦਰ',
    recentActivity: 'ਹਾਲੀਆ ਪ੍ਰੋਸੈਸਿੰਗ ਗਤੀਵਿਧੀ',
    quickUploadBtn: 'ਨਵੀਂ ਫਾਈਲ ਅੱਪਲੋਡ ਕਰੋ',
    uploadTitle: 'ਇੰਟੈਲੀਜੈਂਟ ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ',
    uploadSubtitle: 'AI ਕੱਢਣ ਲਈ PDF, DOCX ਅਤੇ ਤਸਵੀਰਾਂ ਅੱਪਲੋਡ ਕਰੋ',
    dragDropText: 'ਆਪਣੀ ਫਾਈਲ ਇੱਥੇ ਖਿੱਚੋ ਅਤੇ ਛੱਡੋ ਜਾਂ ਬ੍ਰਾਊਜ਼ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT ਦਾ ਸਮਰਥਨ ਕਰਦਾ ਹੈ (ਵੱਧ ਤੋਂ ਵੱਧ 50MB)',
    categoryLabel: 'ਦਸਤਾਵੇਜ਼ ਸ਼੍ਰੇਣੀ',
    uploadingBtn: 'ਪ੍ਰੋਸੈਸਿੰਗ ਜਾਰੀ ਹੈ...',
    uploadStartBtn: 'ਫਾਈਲ ਅੱਪਲੋਡ ਕਰੋ ਅਤੇ ਪ੍ਰੋਸੈਸ ਕਰੋ'
  },
  or: {
    name: 'ଓଡ଼ିଆ (Odia)',
    flag: '🇮🇳',
    loginTitle: 'IDP ପ୍ଲାଟଫର୍ମକୁ ଲଗଇନ୍ କରନ୍ତୁ',
    loginSubtitle: 'AI ଚାଳିତ ବୁଦ୍ଧିମାନ ଦଲିଲ ପ୍ରକ୍ରିୟାକରଣ',
    emailLabel: 'ଇମେଲ ଠିକଣା',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'ପାସୱାର୍ଡ',
    passwordPlaceholder: '••••••••',
    signInBtn: 'ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    noAccount: 'ଆକାଉଣ୍ଟ୍ ନାହିଁ?',
    createAccountLink: 'ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ',
    demoAdminLogin: 'ଡେମୋ ଆଡମିନ୍',
    demoUserLogin: 'ଡେମୋ ୟୁଜର୍',
    registerTitle: 'ଆପଣଙ୍କ ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ',
    registerSubtitle: 'ଇନଭଏସ୍ ଏବଂ ଦଲିଲଗୁଡ଼ିକୁ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ପ୍ରକ୍ରିୟାକରଣ କରନ୍ତୁ',
    fullNameLabel: 'ପୂରା ନାମ',
    fullNamePlaceholder: 'ସୌମ୍ୟରଞ୍ଜନ',
    roleLabel: 'ଆକାଉଣ୍ଟ୍ ଭୂମିକା',
    roleUser: 'ବ୍ୟବହାରକାରୀ (ଅପଲୋଡ୍ ଏବଂ ବିଶ୍ଳେଷଣ)',
    roleAdmin: 'ଆଡମିନିଷ୍ଟ୍ରେଟର (ସମ୍ପୂର୍ଣ୍ଣ ପ୍ରବେଶ)',
    signUpBtn: 'ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ',
    alreadyHaveAccount: 'ପୂର୍ବରୁ ଆକାଉଣ୍ଟ୍ ଅଛି?',
    signInLink: 'ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    navDashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    navUpload: 'ଦଲିଲ ଅପଲୋଡ୍',
    navHistory: 'ଇତିହାସ ଏବଂ ଆର୍କାଇଭ୍',
    navSearch: 'ଖୋଜନ୍ତୁ',
    navChat: 'AI ଦଲିଲ ଚାଟ୍',
    navAdmin: 'ଆଡମିନ୍ କନସୋଲ୍',
    navProfile: 'ମୋର ପ୍ରୋଫାଇଲ୍',
    navSettings: 'ସେଟିଂସମୂହ',
    logoutBtn: 'ସାଇନ୍ ଆଉଟ୍',
    selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    totalDocsCard: 'ମୋଟ ଦଲିଲ',
    storageCard: 'ବ୍ୟବହୃତ ଷ୍ଟୋରେଜ୍',
    ocrCountCard: 'OCR ପ୍ରକ୍ରିୟାକୃତ',
    completionRateCard: 'ସଫଳତା ହାର',
    recentActivity: 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ',
    quickUploadBtn: 'ନୂଆ ଫାଇଲ୍ ଅପଲୋଡ୍ କରନ୍ତୁ',
    uploadTitle: 'ବୁଦ୍ଧିମାନ ଦଲିଲ ଅପଲୋଡ୍',
    uploadSubtitle: 'AI ନିଷ୍କାସନ ପାଇଁ PDF, DOCX ଏବଂ ଚିତ୍ର ଅପଲୋଡ୍ କରନ୍ତୁ',
    dragDropText: 'ଆପଣଙ୍କ ଫାଇଲକୁ ଏଠାରେ ଡ୍ରାଗ୍ ଏବଂ ଡ୍ରପ୍ କରନ୍ତୁ',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT ସମର୍ଥନ କରେ (ସର୍ବାଧିକ 50MB)',
    categoryLabel: 'ଦଲିଲ ବର୍ଗ',
    uploadingBtn: 'ପ୍ରକ୍ରିୟାକରଣ ଚାଲିଛି...',
    uploadStartBtn: 'ଫାଇଲ୍ ଅପଲୋଡ୍ ଏବଂ ପ୍ରକ୍ରିୟାକରଣ କରନ୍ତୁ'
  },
  ur: {
    name: 'اردو (Urdu)',
    flag: '🇮🇳',
    loginTitle: 'IDP پلیٹ فارم میں لاگ ان کریں',
    loginSubtitle: 'مصنوعی ذہانت کے ذریعے دستاویزات کی ذہین پروسیسنگ',
    emailLabel: 'ای میل ایڈریس',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'پاس ورڈ',
    passwordPlaceholder: '••••••••',
    signInBtn: 'سائن ان کریں',
    noAccount: 'کھاتہ نہیں ہے؟',
    createAccountLink: 'نیا کھاتہ بنائیں',
    demoAdminLogin: 'ڈیمو ایڈمن',
    demoUserLogin: 'ڈیمو صارف',
    registerTitle: 'اپنا کھاتہ بنائیں',
    registerSubtitle: 'انوائسز اور دستاویزات کو خود بخود پروسیس کریں',
    fullNameLabel: 'مکمل نام',
    fullNamePlaceholder: 'محمد علی',
    roleLabel: 'کھاتے کا کردار',
    roleUser: 'صارف (اپ لوڈ اور تجزیہ)',
    roleAdmin: 'ایڈمنسٹریٹر (مکمل رسائی)',
    signUpBtn: 'کھاتہ بنائیں',
    alreadyHaveAccount: 'پہلے سے کھاتہ موجود ہے؟',
    signInLink: 'سائن ان کریں',
    navDashboard: 'ڈیش بورڈ',
    navUpload: 'دستاویز اپ لوڈ کریں',
    navHistory: 'ہسٹری اور آرکائیو',
    navSearch: 'تلاش کریں',
    navChat: 'AI دستاویز چیٹ',
    navAdmin: 'ایڈمن کنٹرول',
    navProfile: 'میرا پروفائل',
    navSettings: 'سیٹنگز',
    logoutBtn: 'سائن آؤٹ',
    selectLanguage: 'زبان منتخب کریں',
    totalDocsCard: 'کل دستاویزات',
    storageCard: 'استعمال شدہ اسٹوریج',
    ocrCountCard: 'OCR پروسیس شدہ',
    completionRateCard: 'کامیابی کی شرح',
    recentActivity: 'حالیہ سرگرمی',
    quickUploadBtn: 'نئی فائل اپ لوڈ کریں',
    uploadTitle: 'ذہین دستاویز اپ لوڈ',
    uploadSubtitle: 'AI کے ذریعے تجزیے کے لیے PDF، DOCX اور تصاویر اپ لوڈ کریں',
    dragDropText: 'اپنی فائل یہاں ڈریگ اور ڈراپ کریں',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT کی سہولت (زیادہ سے زیادہ 50MB)',
    categoryLabel: 'دستاویز کا زمرہ',
    uploadingBtn: 'پروسیسنگ جاری ہے...',
    uploadStartBtn: 'فائل اپ لوڈ اور پروسیس کریں'
  },
  as: {
    name: 'অসমীয়া (Assamese)',
    flag: '🇮🇳',
    loginTitle: 'IDP প্লেটফৰ্মত লগইন কৰক',
    loginSubtitle: 'AI চালিত বুদ্ধিমত্তাৰে নথিপত্ৰ প্ৰক্ৰিয়াকৰণ',
    emailLabel: 'ইমেইল ঠিকনা',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'পাছৱৰ্ড',
    passwordPlaceholder: '••••••••',
    signInBtn: 'চাইন্‌ ইন কৰক',
    noAccount: 'একাউণ্ট নাই নেকি?',
    createAccountLink: 'একাউণ্ট সৃষ্টি কৰক',
    demoAdminLogin: 'ডেমো এডমিন',
    demoUserLogin: 'ডেমো ব্যৱহাৰকাৰী',
    registerTitle: 'আপোনাৰ একাউণ্ট সৃষ্টি কৰক',
    registerSubtitle: 'ইনভইচ আৰু নথি স্বয়ংক্ৰিয়ভাৱে প্ৰক্ৰিয়া কৰক',
    fullNameLabel: 'সম্পূৰ্ণ নাম',
    fullNamePlaceholder: 'বৰুৱা',
    roleLabel: 'একাউণ্ট ভূমিকা',
    roleUser: 'ব্যৱহাৰকাৰী (আপলোড আৰু বিশ্লেষণ)',
    roleAdmin: 'প্ৰশাসক (সম্পূৰ্ণ প্ৰৱেশ)',
    signUpBtn: 'একাউণ্ট সৃষ্টি কৰক',
    alreadyHaveAccount: 'ইতিমধ্যে একাউণ্ট আছে নেকি?',
    signInLink: 'চাইন্‌ ইন কৰক',
    navDashboard: 'ড্যাশবৰ্ড',
    navUpload: 'নথি আপলোড কৰক',
    navHistory: 'ইতিহাস আৰু আৰ্কাইভ',
    navSearch: 'সন্ধান কৰক',
    navChat: 'AI নথি চ্যাট',
    navAdmin: 'এডমিন কনচোল',
    navProfile: 'মোৰ প্ৰফাইল',
    navSettings: 'ছেটিংছ',
    logoutBtn: 'চাইন্‌ আউট',
    selectLanguage: 'ভাষা বাছনি কৰক',
    totalDocsCard: 'মুঠ নথি',
    storageCard: 'ব্যৱহৃত ষ্ট’ৰেজ',
    ocrCountCard: 'OCR প্ৰক্ৰিয়াকৃত',
    completionRateCard: 'সফলতাৰ হাৰ',
    recentActivity: 'শেহতীয়া প্ৰক্ৰিয়াকৰণ কাৰ্যকলাপ',
    quickUploadBtn: 'নতুন ফাইল আপলোড কৰক',
    uploadTitle: 'বুদ্ধিমত্তাৰে নথি আপলোড',
    uploadSubtitle: 'AI এক্সট্ৰেক্সনৰ বাবে PDF, DOCX আৰু ছবি আপলোড কৰক',
    dragDropText: 'আপোনাৰ ফাইল ইয়াত ড্ৰেগ আৰু ড্রপ কৰক',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT সমৰ্থন কৰে (সর্বোচ্চ 50MB)',
    categoryLabel: 'নথি শ্ৰেণী',
    uploadingBtn: 'প্ৰক্ৰিয়াকৰণ চলি আছে...',
    uploadStartBtn: 'ফাইল আপলোড আৰু প্ৰক্ৰিয়া কৰক'
  },
  es: {
    name: 'Español (Spanish)',
    flag: '🇪🇸',
    loginTitle: 'Iniciar sesión en la Plataforma IDP',
    loginSubtitle: 'Procesamiento Inteligente de Documentos con Inteligencia Artificial',
    emailLabel: 'Correo Electrónico',
    emailPlaceholder: 'tu@ejemplo.com',
    passwordLabel: 'Contraseña',
    passwordPlaceholder: '••••••••',
    signInBtn: 'Iniciar Sesión',
    noAccount: '¿No tienes una cuenta?',
    createAccountLink: 'Crear una cuenta',
    demoAdminLogin: 'Acceso Administrador Demo',
    demoUserLogin: 'Acceso Usuario Demo',
    registerTitle: 'Crea tu cuenta',
    registerSubtitle: 'Comienza a procesar facturas, contratos y documentos automáticamente',
    fullNameLabel: 'Nombre Completo',
    fullNamePlaceholder: 'Juan Pérez',
    roleLabel: 'Rol de la Cuenta',
    roleUser: 'Usuario (Cargar y Analizar)',
    roleAdmin: 'Administrador (Acceso Total)',
    signUpBtn: 'Crear Cuenta',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    signInLink: 'Iniciar Sesión',
    navDashboard: 'Panel Principal',
    navUpload: 'Cargar Documento',
    navHistory: 'Historial y Archivo',
    navSearch: 'Búsqueda Global',
    navChat: 'Chat IA de Documentos',
    navAdmin: 'Consola Admin',
    navProfile: 'Mi Perfil',
    navSettings: 'Configuración',
    logoutBtn: 'Cerrar Sesión',
    selectLanguage: 'Seleccionar Idioma',
    totalDocsCard: 'Documentos Totales',
    storageCard: 'Almacenamiento Usado',
    ocrCountCard: 'OCR Procesados',
    completionRateCard: 'Tasa de Éxito',
    recentActivity: 'Actividad Reciente',
    quickUploadBtn: 'Cargar Nuevo Archivo',
    uploadTitle: 'Carga Inteligente de Documentos',
    uploadSubtitle: 'Cargue PDF, DOCX, imágenes escaneadas o archivos de texto',
    dragDropText: 'Arrastre y suelte su archivo aquí',
    supportedFormats: 'Admite PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT (Máx. 50 MB)',
    categoryLabel: 'Categoría del Documento',
    uploadingBtn: 'Procesando...',
    uploadStartBtn: 'Cargar y Procesar Archivo'
  },
  fr: {
    name: 'Français (French)',
    flag: '🇫🇷',
    loginTitle: 'Connexion à la Plateforme IDP',
    loginSubtitle: 'Traitement Intelligent des Documents propulsé par l\'IA',
    emailLabel: 'Adresse E-mail',
    emailPlaceholder: 'vous@exemple.com',
    passwordLabel: 'Mot de passe',
    passwordPlaceholder: '••••••••',
    signInBtn: 'Se Connecter',
    noAccount: 'Vous n\'avez pas de compte ?',
    createAccountLink: 'Créer un compte',
    demoAdminLogin: 'Démo Admin Rapide',
    demoUserLogin: 'Démo Utilisateur Rapide',
    registerTitle: 'Créer votre compte',
    registerSubtitle: 'Traitez automatiquement vos factures, contrats et documents',
    fullNameLabel: 'Nom Complet',
    fullNamePlaceholder: 'Jean Dupont',
    roleLabel: 'Rôle du Compte',
    roleUser: 'Utilisateur (Téléverser & Analyser)',
    roleAdmin: 'Administrateur (Accès Complet)',
    signUpBtn: 'Créer un Compte',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    signInLink: 'Se Connecter',
    navDashboard: 'Tableau de bord',
    navUpload: 'Téléverser un document',
    navHistory: 'Historique et Archives',
    navSearch: 'Recherche Globale',
    navChat: 'Chat IA Document',
    navAdmin: 'Console Admin',
    navProfile: 'Mon Profil',
    navSettings: 'Paramètres',
    logoutBtn: 'Déconnexion',
    selectLanguage: 'Choisir la Langue',
    totalDocsCard: 'Total des Documents',
    storageCard: 'Stockage Utilisé',
    ocrCountCard: 'OCR Traités',
    completionRateCard: 'Taux de Réussite',
    recentActivity: 'Activité Récente',
    quickUploadBtn: 'Téléverser un fichier',
    uploadTitle: 'Téléversement Intelligent',
    uploadSubtitle: 'Téléversez PDF, DOCX, images scannées ou fichiers texte',
    dragDropText: 'Glissez-déposez votre fichier ici',
    supportedFormats: 'Prend en charge PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT (Max 50 Mo)',
    categoryLabel: 'Catégorie du Document',
    uploadingBtn: 'Traitement...',
    uploadStartBtn: 'Téléverser et Traiter'
  },
  de: {
    name: 'Deutsch (German)',
    flag: '🇩🇪',
    loginTitle: 'Anmelden bei IDP-Plattform',
    loginSubtitle: 'Intelligente Dokumentenverarbeitung mit KI',
    emailLabel: 'E-Mail-Adresse',
    emailPlaceholder: 'sie@beispiel.de',
    passwordLabel: 'Passwort',
    passwordPlaceholder: '••••••••',
    signInBtn: 'Anmelden',
    noAccount: 'Noch kein Konto?',
    createAccountLink: 'Konto erstellen',
    demoAdminLogin: 'Schnell-Demo Admin',
    demoUserLogin: 'Schnell-Demo Benutzer',
    registerTitle: 'Erstellen Sie Ihr Konto',
    registerSubtitle: 'Automatisieren Sie Rechnungen, Verträge und Dokumente',
    fullNameLabel: 'Vollständiger Name',
    fullNamePlaceholder: 'Max Mustermann',
    roleLabel: 'Konto-Rolle',
    roleUser: 'Benutzer (Hochladen & Analysieren)',
    roleAdmin: 'Administrator (Vollzugriff)',
    signUpBtn: 'Konto Erstellen',
    alreadyHaveAccount: 'Bereits ein Konto?',
    signInLink: 'Anmelden',
    navDashboard: 'Dashboard',
    navUpload: 'Dokument Hochladen',
    navHistory: 'Verlauf & Archiv',
    navSearch: 'Suche',
    navChat: 'KI-Dokumenten-Chat',
    navAdmin: 'Admin-Konsole',
    navProfile: 'Mein Profil',
    navSettings: 'Einstellungen',
    logoutBtn: 'Abmelden',
    selectLanguage: 'Sprache Wählen',
    totalDocsCard: 'Gesamte Dokumente',
    storageCard: 'Verwendeter Speicher',
    ocrCountCard: 'OCR Verarbeitet',
    completionRateCard: 'Erfolgsquote',
    recentActivity: 'Neueste Aktivitäten',
    quickUploadBtn: 'Neue Datei Hochladen',
    uploadTitle: 'Intelligenter Dokumenten-Upload',
    uploadSubtitle: 'Laden Sie PDF, DOCX, Bilder oder Textdateien hoch',
    dragDropText: 'Ziehen Sie Ihre Datei hierher',
    supportedFormats: 'Unterstützt PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT (Max. 50 MB)',
    categoryLabel: 'Dokumentenkategorie',
    uploadingBtn: 'Verarbeitung...',
    uploadStartBtn: 'Datei Hochladen & Verarbeiten'
  },
  zh: {
    name: '中文 (Chinese)',
    flag: '🇨🇳',
    loginTitle: '登录到 IDP 智能文档平台',
    loginSubtitle: 'AI 驱动的企业级智能文档处理平台',
    emailLabel: '电子邮件地址',
    emailPlaceholder: 'you@example.com',
    passwordLabel: '密码',
    passwordPlaceholder: '••••••••',
    signInBtn: '立即登录',
    noAccount: '还没有账号？',
    createAccountLink: '注册新账号',
    demoAdminLogin: '快速演示管理员',
    demoUserLogin: '快速演示用户',
    registerTitle: '创建您的账号',
    registerSubtitle: '自动处理发票、合同和扫描文档',
    fullNameLabel: '全名',
    fullNamePlaceholder: '张伟',
    roleLabel: '账号角色',
    roleUser: '普通用户（上传与分析）',
    roleAdmin: '管理员（完整权限）',
    signUpBtn: '立即注册',
    alreadyHaveAccount: '已有账号？',
    signInLink: '去登录',
    navDashboard: '控制台仪表板',
    navUpload: '上传新文档',
    navHistory: '文档历史归档',
    navSearch: '全局搜索',
    navChat: 'AI 文档对话',
    navAdmin: '管理后台',
    navProfile: '个人中心',
    navSettings: '系统设置',
    logoutBtn: '退出登录',
    selectLanguage: '选择语言',
    totalDocsCard: '文档总数',
    storageCard: '已用存储空间',
    ocrCountCard: 'OCR 处理数',
    completionRateCard: '处理成功率',
    recentActivity: '最近处理活动',
    quickUploadBtn: '上传新文件',
    uploadTitle: '智能文档上传',
    uploadSubtitle: '上传 PDF、DOCX、图片或文本文件，进行 AI 提取',
    dragDropText: '将文件拖放到此处，或点击浏览文件',
    supportedFormats: '支持 PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT (最大 50MB)',
    categoryLabel: '文档分类',
    uploadingBtn: '处理中...',
    uploadStartBtn: '上传并开始分析'
  },
  ja: {
    name: '日本語 (Japanese)',
    flag: '🇯🇵',
    loginTitle: 'IDPプラットフォームにログイン',
    loginSubtitle: 'AIを活用したエンタープライズ文書処理',
    emailLabel: 'メールアドレス',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'パスワード',
    passwordPlaceholder: '••••••••',
    signInBtn: 'サインイン',
    noAccount: 'アカウントをお持ちでないですか？',
    createAccountLink: 'アカウント作成',
    demoAdminLogin: 'デモ管理者で試す',
    demoUserLogin: 'デモユーザーで試す',
    registerTitle: 'アカウントを作成',
    registerSubtitle: '請求書や契約書の自動抽出を開始しましょう',
    fullNameLabel: '氏名',
    fullNamePlaceholder: '山田 太郎',
    roleLabel: 'アカウントの役割',
    roleUser: '一般ユーザー（アップロード・解析）',
    roleAdmin: '管理者（フルアクセス）',
    signUpBtn: 'アカウントを作成',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    signInLink: 'サインイン',
    navDashboard: 'ダッシュボード',
    navUpload: '文書アップロード',
    navHistory: '履歴とアーカイブ',
    navSearch: '検索',
    navChat: 'AI 文書チャット',
    navAdmin: '管理コンソール',
    navProfile: 'プロフィール',
    navSettings: '設定',
    logoutBtn: 'ログアウト',
    selectLanguage: '言語を選択',
    totalDocsCard: '総ドキュメント数',
    storageCard: '使用ストレージ容量',
    ocrCountCard: 'OCR 処理件数',
    completionRateCard: '処理成功率',
    recentActivity: '最近の処理アクティビティ',
    quickUploadBtn: '新しいファイルをアップロード',
    uploadTitle: 'インテリジェント文書アップロード',
    uploadSubtitle: 'PDF、DOCX、画像、テキストファイルをアップロードしてAI抽出を開始',
    dragDropText: 'ここにファイルをドラッグ＆ドロップ',
    supportedFormats: 'PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT (最大 50MB)',
    categoryLabel: 'ドキュメントカテゴリ',
    uploadingBtn: '処理中...',
    uploadStartBtn: 'ファイルをアップロードして解析'
  },
  ar: {
    name: 'العربية (Arabic)',
    flag: '🇦🇪',
    loginTitle: 'تسجيل الدخول إلى منصة IDP',
    loginSubtitle: 'معالجة المستندات الذكية مدعومة بالذكاء الاصطناعي',
    emailLabel: 'البريد الإلكتروني',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'كلمة المرور',
    passwordPlaceholder: '••••••••',
    signInBtn: 'تسجيل الدخول',
    noAccount: 'ليس لديك حساب؟',
    createAccountLink: 'إنشاء حساب جديد',
    demoAdminLogin: 'دخول سريع كمسؤول',
    demoUserLogin: 'دخول سريع كمستخدم',
    registerTitle: 'إنشاء حسابك',
    registerSubtitle: 'ابدأ بمعالجة الفواتير والعقود تلقائيًا',
    fullNameLabel: 'الاسم الكامل',
    fullNamePlaceholder: 'أحمد محمود',
    roleLabel: 'دور الحساب',
    roleUser: 'مستخدم (رفع وتحليل)',
    roleAdmin: 'مسؤول (صلاحيات كاملة)',
    signUpBtn: 'إنشاء الحساب',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    signInLink: 'تسجيل الدخول',
    navDashboard: 'لوحة التحكم',
    navUpload: 'رفع مستند',
    navHistory: 'سجل المستندات',
    navSearch: 'البحث',
    navChat: 'محادثة الذكاء الاصطناعي',
    navAdmin: 'لوحة الإدارة',
    navProfile: 'الملف الشخصي',
    navSettings: 'الإعدادات',
    logoutBtn: 'تسجيل الخروج',
    selectLanguage: 'اختر اللغة',
    totalDocsCard: 'إجمالي المستندات',
    storageCard: 'المساحة المستخدمة',
    ocrCountCard: 'معالجة OCR',
    completionRateCard: 'نسبة النجاح',
    recentActivity: 'النشاط الحديث',
    quickUploadBtn: 'رفع ملف جديد',
    uploadTitle: 'رفع المستندات الذكي',
    uploadSubtitle: 'قم برفع ملفات PDF و DOCX والصور لاستخراج البيانات',
    dragDropText: 'قم بسحب وإسقاط الملف هنا',
    supportedFormats: 'يدعم PDF, DOCX, PNG, JPG, WEBP, TIFF, TXT (حد أقصى 50MB)',
    categoryLabel: 'فئة المستند',
    uploadingBtn: 'جاري المعالجة...',
    uploadStartBtn: 'رفع ومعالجة الملف'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('idp_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('idp_language', lang);
    document.dir = (lang === 'ar' || lang === 'ur') ? 'rtl' : 'ltr';
  }, [lang]);

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
